// <auto-generated />
using MicroRabbit.Gestion.Responsable.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroRabbit.Gestion.Responsable.Data.Migrations
{
    [DbContext(typeof(Gestion_Responsable_DBContext))]
    partial class Gestion_Responsable_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicroRabbit.Gestion.Responsable.Domain.Models.Filiale", b =>
                {
                    b.Property<int>("FilialeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Nom");

                    b.HasKey("FilialeID");

                    b.ToTable("Filiales");
                });

            modelBuilder.Entity("MicroRabbit.Gestion.Responsable.Domain.Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilialeID");

                    b.Property<string>("Login");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.HasKey("UtilisateurID");

                    b.HasIndex("FilialeID");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MicroRabbit.Gestion.Responsable.Domain.Models.Utilisateur", b =>
                {
                    b.HasOne("MicroRabbit.Gestion.Responsable.Domain.Models.Filiale", "Filiale")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("FilialeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
